# Cache .npm instead of node_modules because the later one will be automatically removed by `npm ci`
# https://docs.npmjs.com/cli/ci.html
# https://docs.npmjs.com/cli/cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${CI_PROJECT_DIR}/.npm/
    - ${CI_PROJECT_DIR}/.cypress/

before_script:
  - export CYPRESS_CACHE_FOLDER=${CI_PROJECT_DIR}/.cypress
  - npm config set cache ${CI_PROJECT_DIR}/.npm
  - npm ci --prefer-offline

build:
  image: node:11
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:11
  stage: test
  script:
    - npm run test:unit

e2e test:
  image: cypress/base:10
  stage: test
  script:
    - $(npm bin)/cypress verify
    - npm run test:e2e -- --headless --record --key ${CYPRESS_RECORD_KEY}

deploy:
  image: alpine
  stage: deploy
  before_script: []
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ root@51.15.199.149:/var/www/bus/
