# Cache .npm instead of node_modules because the later one will be automatically removed by `npm ci`
# https://docs.npmjs.com/cli/ci.html
# https://docs.npmjs.com/cli/cache

stages:
  - build
  - test
  - staging
  - lighthouse
  - deploy

before_script:
  - export CYPRESS_CACHE_FOLDER=${CI_PROJECT_DIR}/.cypress
  - npm config set cache ${CI_PROJECT_DIR}/.npm
  - npm ci --prefer-offline

build:
  image: node:11
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ${CI_PROJECT_DIR}/.npm/
      - ${CI_PROJECT_DIR}/.cypress/
  tags:
    - docker
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:11
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ${CI_PROJECT_DIR}/.npm/
      - ${CI_PROJECT_DIR}/.cypress/
    policy: pull
  tags:
    - docker
  script:
    - npm run test:unit

e2e test:
  image: cypress/browsers:chrome69
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ${CI_PROJECT_DIR}/.npm/
      - ${CI_PROJECT_DIR}/.cypress/
    policy: pull
  tags:
    - docker
  script:
    - npm run test:e2e -- --headless --browser chrome

staging:
  image: instrumentisto/rsync-ssh
  stage: staging
  tags:
    - docker
  before_script: []
  script:
    - mkdir -p ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - 'echo -e "User-agent: *\nDisallow: /\n" > dist/robots.txt'
    - rsync -rav --delete dist/ root@51.15.199.149:/var/www/bus-staging/

lighthouse:
  image: cypress/browsers:chrome69
  stage: lighthouse
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ${CI_PROJECT_DIR}/.npm/
      - ${CI_PROJECT_DIR}/.cypress/
    policy: pull
  tags:
    - docker
  script:
    - mkdir lighthouse
    - ./node_modules/.bin/lighthouse https://bus-staging.kiwiberry.nz/
      --output json html
      --output-path ./lighthouse/audit
      --chrome-flags="--headless"
    - node ./lighthouse-ci.js ./lighthouse/audit.report.json
  artifacts:
    expire_in: 1 week
    paths:
      -  report.html

deploy:
  image: instrumentisto/rsync-ssh
  stage: deploy
  tags:
    - docker
  before_script: []
  script:
    - mkdir -p ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ root@51.15.199.149:/var/www/bus/
