[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal
# Git-backed deploys.
ID = "5d4a6825-e06a-4e34-ab06-6b344134bf97"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# PER-DEPLOY.

[[redirects]]
  from = "/index.html"
  to = "/"

  # The default HTTP status code is 301, but you can define a different one.
  status = 301

  # By default, redirects won't be applied if there's a file with the same
  # path as the one defined in the `from` property. Setting `force` to `true`
  # will make the redirect rule take precedence over any existing files.
  force = true

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Long-term cache by default.
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

  # And here are the exceptions:
  for = "/"
  [headers.values]
    Cache-Control = "no-cache"

  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

  for = "/robots.txt"
  [headers.values]
    Cache-Control = "max-age=86400"
